saashop/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [path("", views.DescriptionView.as_view(), name="about")]

saashop/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"
urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="item_list",
    ),
    path(
        "new/",
        views.NewItemListView.as_view(),
        name="new_item_list",
    ),
    path(
        "friday/",
        views.FridayItemListView.as_view(),
        name="friday_item_list",
    ),
    path(
        "unverified/",
        views.UnverifiedItemListView.as_view(),
        name="unverified_item_list",
    ),
    path(
        "<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
]

saashop/feedback/urls.py
from django.urls import path

from feedback import views

app_name = "feedback"
urlpatterns = [path("", views.FeedbackView.as_view(), name="feedback")]

saashop/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

saashop/rating/urls.py
from django.urls import path

from rating import views

app_name = "rating"

urlpatterns = [
    path(
        "delete/<int:pk>/",
        views.RatingDeleteView.as_view(),
        name="delete_rating",
    ),
    path(
        "update/<int:pk>/",
        views.RatingUpdateView.as_view(),
        name="update_rating",
    ),
]

saashop/saashop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("rating/", include("rating.urls")),
    path("statistics/", include("global_statistics.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls), name="users_default"),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT and settings.USE_LOCAL_MEDIA:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

saashop/users/urls.py
from django.contrib.auth import views
from django.urls import path

import users.forms
import users.views

app_name = "users"

urlpatterns = [
    path("signup/", users.views.UserSignupView.as_view(), name="signup"),
    path("users/", users.views.UserListView.as_view(), name="user_list"),
    path(
        "user/<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path("profile/", users.views.ProfileEditView.as_view(), name="profile"),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            form_class=users.forms.MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.MyPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=users.forms.MyPasswordConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "activate/<str:token>/",
        users.views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path(
        "reactivate/<str:token>/",
        users.views.ReactivateAccountView.as_view(),
        name="reactivate_account",
    ),
]

saashop/rating/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from catalog.models import Item
from users.models import User


__all__ = ()


class RatingManager(models.Manager):
    def average_rating(self, item_id):
        queryset = self.get_queryset().filter(item_id=item_id)
        return get_rating_stats(queryset.all())

    def get_rating_with_user(self):
        return (
            self.get_queryset()
            .select_related(Rating.user.field.name)
            .select_related(
                f"{Rating.user.field.name}__profile",
            )
        )

    def get_item_with_rating(self, item_id):
        return (
            Item.objects.item_detail(item_id)
            .select_related(Item.main_image.field.name)
            .prefetch_related(
                models.Prefetch(
                    "ratings",
                    queryset=self.get_rating_with_user(),
                ),
            )
        )

    def get_rating_by_item_and_user(self, user_id, item_id):
        return self.get_queryset().filter(user_id=user_id, item_id=item_id)


def get_rating_stats(ratings):
    count_of_rating = len(ratings)
    if not count_of_rating:
        return {
            "count": 0,
            "avg": None,
        }
    average_rating = round(
        sum(r.rating for r in ratings) / count_of_rating,
        1,
    )
    return {
        "count": count_of_rating,
        "avg": average_rating,
    }


class Rating(models.Model):
    objects = RatingManager()

    RATING_CHOICES = (
        (1, "Ненависть"),
        (2, "Неприязнь"),
        (3, "Нейтрально"),
        (4, "Обожание"),
        (5, "Любовь"),
    )

    rating = models.PositiveIntegerField(
        "оценка",
        choices=RATING_CHOICES,
    )
    text = models.TextField(
        "ваш отзыв о товаре",
        blank=True,
        null=True,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="ratings",
        related_query_name="ratings",
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name="ratings",
        related_query_name="ratings",
    )
    created_at = models.DateTimeField(
        _("created_at_utc_models"),
        null=True,
        auto_now_add=True,
    )

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        unique_together = ("user", "item")

saashop/rating/forms.py
from django import forms

from rating.models import Rating
from saashop.mixins import BaseFormMixin

__all__ = ()


class RatingForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(RatingForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = Rating
        fields = (
            model.rating.field.name,
            model.text.field.name,
        )

        exclude = (
            model.user.field.name,
            model.item.field.name,
            model.created_at.field.name,
        )

        widgets = {
            model.text.field.name: forms.Textarea(
                attrs={
                    "rows": "5",
                },
            ),
        }


class RatingAdminForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = "__all__"

    def clean(self):
        cleaned_data = super().clean()
        user = cleaned_data.get("user")
        item = cleaned_data.get("item")

        existing_rating = Rating.objects.filter(user=user, item=item).first()

        if existing_rating:
            raise forms.ValidationError(
                "Пользователь уже оставлял свой отзыв на этот товар",
            )

saashop/rating/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View

from rating.forms import RatingForm
from rating.models import Rating

__all__ = ()


@method_decorator(login_required, name="dispatch")
class RatingDeleteView(View):
    def get(self, request, pk):
        rating = get_object_or_404(
            Rating.objects,
            pk=pk,
        )
        item_id = rating.item.id
        if request.user.is_superuser or request.user.id == rating.user.id:
            rating.delete()
            messages.success(
                request,
                "Отзыв удалён",
            )
            return redirect("catalog:item_detail", pk=item_id)
        return HttpResponseForbidden()


@method_decorator(login_required, name="dispatch")
class RatingUpdateView(View):
    def post(self, request, pk):
        rating = get_object_or_404(
            Rating.objects.all(),
            pk=pk,
        )
        if not request.user.is_superuser and request.user.id != rating.user.id:
            return HttpResponseForbidden()
        form = RatingForm(request.POST, instance=rating)
        if form.is_valid():
            if rating:
                rating.text = form.cleaned_data["text"]
                rating.rating = form.cleaned_data["rating"]
                rating.save()
                messages.success(
                    request,
                    "Изменения сохранены",
                )
                return redirect("catalog:item_detail", pk=rating.item.id)
        messages.error(
            request,
            "Форма заполнена неверно",
        )
        return redirect("catalog:item_detail", pk=rating.item.id)

saashop/templates/includes/birthday_users.html
{% if users_with_birthday %}
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#usersBirthday">
    Наши именниники
  </button>
  <div class="modal fade" id="usersBirthday" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Сегодня празднуют день рождения:</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>
            <ul>
            {% for user in users_with_birthday %}
              <li><a href="{% url 'users:user_detail' pk=user.id %}">{{ user.username }}</a></li>
            {% endfor %}
            </ul>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>
{% endif %}

saashop/templates/includes/footer.html
{% load static i18n %}

<footer class="site-footer">
    <div class="container">
        <div class="site-footer-inner">
            <div class="brand footer-brand">
                <a href="{% url 'homepage:homepage' %}">
                    <img width="32px" height="32px" class="header-logo-image" src="{% static 'img/saas.png' %}" alt="Logo">
                </a>
            </div>
            <ul class="footer-links list-reset">
                <li>
                    <a href="https://github.com/SaaShopOfficial">GitHub</a>
                </li>
            </ul>
            <ul class="footer-social-links list-reset">
            </ul>
            <div class="footer-copyright">&copy; <span id="footerYear">{% now "Y" %}</span>&nbsp; SaaShop, {% translate "all_rights_reserved" %}</div>
        </div>
    </div>
</footer>

saashop/templates/includes/form.html
{% for field in form %}
    <div class="form-group mb-3">
        <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error|safe }}
                </div>
            {% endfor %}
        {% endif %}
        {% if field.help_text %}
            <div class="form-text text-muted">
                <p>{{ field.help_text|safe }}</p>
            </div>
        {% endif %}
    </div>
{% endfor %}
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            {{ error|safe }}
        {% endfor %}
    </div>
{% endif %}

saashop/templates/includes/header.html
{% load static i18n %}
<header>
  <nav class="navbar navbar-expand-xl bg-body-tertiary rounded d-flex flex-wrap saas_navbar" aria-label="SaaShopnavbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
        <img src="{% static 'img/saas.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
          SaaShop
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#SaaShop" aria-controls="SaaShop" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% with request.resolver_match.view_name as view_name %}
      <div class="collapse navbar-collapse justify-content-end flex-nowrap" id="SaaShop">
        <ul class="nav nav-pills nav-fill mt-xs-2 mt-md-2 mt-lg-2 mt-xl-0 mt-2">
          <li class="nav-item"><a href="{% url 'homepage:homepage' %}" {% if view_name == "homepage:homepage" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "home" %}</a></li>
          <li class="nav-item"><a href="{% url 'about:about' %}" {% if view_name == "about:about" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "about" %}</a></li>
          <li class="nav-item"><a href="{% url 'catalog:item_list' %}" {% if view_name == "catalog:item_list" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "item_list" %}</a></li>
          <li class="nav-item"><a href="{% url 'feedback:feedback' %}" {% if view_name == "feedback:feedback" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "feedback" %}</a></li>
          {% if request.user.is_anonymous %}
          <li class="nav-item"><a href="{% url 'users:login' %}" {% if view_name == "users:login" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "login" %}</a></li>
          {% else %}
          <li class="nav-item"><a href="{% url 'users:logout' %}" {% if view_name == "users:logout" %}aria-current="page" class="nav-link active"{% else %}class="nav-link"{% endif %}>{% translate "logout" %}</a></li>
          {% endif %}
          {% if request.user.is_superuser %}
          <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">{% translate "admin_panel" %}</a></li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <select onchange="this.form.submit()" class="form-select ms-lg-2 mt-xs-2 mt-md-2 mt-lg-2 mt-xl-0 mt-2" name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                  <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                      {{ language.name_local }} ({{ language.code }})
                  </option>
              {% endfor %}
          </select>
        </form>
      </div>
      {% endwith %}
    </div>
  </nav>
</header>

saashop/templates/includes/item_card.html
{% load i18n %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        {% comment %} {% if item.main_image %}
            {{ item.main_image.image_in_template }}
        {% else %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="300px" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>{% translate "no_image" %}</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
            </svg>
        {% endif %} {% endcomment %}
        <div class="card-body">
            <a href="{% url 'catalog:item_detail' pk=item.id %}">
                <h5 class="card-title text-white">{{ item.name }}</h5>
                <p class="card-text">{{ item.text|truncatewords_html:10|striptags|safe }}</p>
                {% if item.category.name %}
                <h5>{% translate "category" %}:</h5>
                <p class="card-text">
                    <span class="badge rounded-pill text-bg-warning">{{ item.category.name }}</span>
                </p>
                {% endif %}
                <h5>{% translate "tags" %}:</h5>
                <p>
                    {% for tag in item.tags.all %}
                    <span class="badge rounded-pill text-bg-warning">{{ tag.name }}</span>
                    {% empty %}
                    {% translate "empty_plural" %}
                    {% endfor %}
                </p>
            </a>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user.is_superuser %}
                    <a href="{% url 'admin:catalog_item_change' item.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">{% translate "edit" %}</button></a>
                    {% endif %}
                </div>
            <!-- <small class="text-body-secondary">9 mins</small> -->
            </div>
        </div>
    </div>
</div>

saashop/templates/includes/rating.html
{% load thumbnail i18n %}

{% if user.id == rating.user.id %}
<div class="modal fade" id="ratingEdit{{ rating.id }}" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Редактировать отзыв</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="{% url 'rating:update_rating' pk=rating.id %}">
                {% csrf_token %}
                {% include "includes/form.html" %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
          <input class="btn btn-primary" type="submit" value="Отправить">
            </form>
        </div>
      </div>
    </div>
</div>
{% endif %}

<div class="ratings_section">
    <div class="container d-flex justify-content-center mt-10">
        <div class="row w-100">
            <div class="col-md-12">
                <div class="card">
                    <div class="comment-widgets m-b-20">
                        <div class="d-flex flex-row comment-row">
                            <div class="p-2">
                                <span class="round">
                                    {% thumbnail rating.user.profile.image "50x50" as avatar %}
                                        <img src="{{ avatar.url }}" alt="User Avatar" width="50px">
                                    {% empty %}
                                        <svg height="50px" width="50px" class="round" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Avatar" preserveAspectRatio="xMidYMid slice" focusable="false">
                                            <title>{% translate "no_image" %}</title>
                                            <rect width="100%" height="100%" fill="#55595c"></rect>
                                        </svg>
                                    {% endthumbnail %}
                                </span>
                            </div>
                            <div class="comment-text w-100">
                                <div class="row">
                                    <h5 class="col">{{ rating.user.username }}</h5>
                                </div>
                                <div class="row">
                                    <div class="comment-footer col">
                                        <span class="date">{{ rating.created_at }} (UTC)</span>
                                        <span class="action-icons">
                                            {% if user.id == rating.user.id %}
                                            <a data-bs-toggle="modal" data-bs-target="#ratingEdit{{ rating.id }}" href="#"><i class="fa fa-pencil"></i></a>
                                            {% endif %}
                                            {% if user.id == rating.user.id or user.is_superuser %}
                                            <a href="{% url 'rating:delete_rating' pk=rating.id %}"><i class="fa fa-trash"></i></a>
                                            {% endif %}
                                        </span>
                                    </div>
                                </div>
                                <p class="m-b-5 m-t-10">Оценка: {{ rating.get_rating_display }}</p>
                                <p class="m-b-5 m-t-10">{{ rating.text|safe|linebreaks }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

saashop/templates/includes/toasts.html
{% load static %}
{% if messages %}
    <div class="toast-container toast-custom" aria-live="polite" aria-atomic="true">
        {% for message in messages %}
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img src="{% static 'img/saas.png' %}" class="bd-placeholder-img rounded me-2" width="20" height="20">
                    <strong class="me-auto">SaaShop</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}