saashop/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [path("", views.DescriptionView.as_view(), name="about")]

saashop/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"
urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="item_list",
    ),
    path(
        "new/",
        views.NewItemListView.as_view(),
        name="new_item_list",
    ),
    path(
        "friday/",
        views.FridayItemListView.as_view(),
        name="friday_item_list",
    ),
    path(
        "unverified/",
        views.UnverifiedItemListView.as_view(),
        name="unverified_item_list",
    ),
    path(
        "<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
]

saashop/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

saashop/saashop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("rating/", include("rating.urls")),
    path("statistics/", include("global_statistics.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls), name="users_default"),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT and settings.USE_LOCAL_MEDIA:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

saashop/homepage/forms.py
from django import forms

from saashop.mixins import BaseFormMixin

__all__ = ("EchoForm",)


class EchoForm(forms.Form, BaseFormMixin):
    text = forms.CharField(
        label="Текст",
        help_text="Введите какой-нибудь текст",
        widget=forms.Textarea(attrs={"rows": 5}),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super(EchoForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

saashop/homepage/views.py
from http import HTTPStatus

from django.http import HttpResponse
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views import View

import catalog.models
from homepage.forms import EchoForm

__all__ = ()


class HomeView(View):
    template_name = "homepage/main.html"

    def get(self, request):
        items = catalog.models.Item.objects.on_main()
        features = [
            {"title": _("feature_1_title"), "content": _("feature_1_content")},
            {"title": _("feature_2_title"), "content": _("feature_2_content")},
            {"title": _("feature_3_title"), "content": _("feature_3_content")},
            {"title": _("feature_4_title"), "content": _("feature_4_content")},
            {"title": _("feature_5_title"), "content": _("feature_5_content")},
            {"title": _("feature_6_title"), "content": _("feature_6_content")},
        ]
        context = {
            "items": items,
            "features": features,
        }
        return render(
            request,
            template_name=self.template_name,
            context=context,
        )


class CoffeeView(View):
    def get(self, request):
        if request.user.is_authenticated:
            profile = request.user.profile
            profile.coffee_count += 1
            profile.save()
        return HttpResponse("Я чайник", status=HTTPStatus.IM_A_TEAPOT)


class EchoView(View):
    template_name = "homepage/echo.html"
    form_class = EchoForm

    def get(self, request):
        context = {
            "form": self.form_class,
        }
        return render(
            request,
            template_name=self.template_name,
            context=context,
        )


class EchoSubmitView(View):
    template_name = "homepage/echo.html"

    def post(self, request):
        form = EchoForm(request.POST or None)
        if form.is_valid():
            text = form.cleaned_data["text"]
            return HttpResponse(text)
        form = EchoForm()
        context = {"form": form}
        return render(
            request,
            template_name=self.template_name,
            context=context,
        )

    def get(self, request):
        return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)

saashop/templates/homepage/echo.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h1>Эхо</h1>
    <form method="post" action="{% url 'homepage:echo_submit' %}">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="Отправить">
    </form>
</div>

{% endblock %}

saashop/templates/homepage/main.html
{% extends "base.html" %}
{% block main %}
{% load static i18n %}
<script src="{% static 'js/anime.min.js' %}"></script>
<script src="{% static 'js/scrollreveal.min.js' %}"></script>
<div class="body-wrap">
    <header class="site-header">
        <div class="container">
            <div class="site-header-inner">
                <div class="brand header-brand">
                    <h1 class="m-0">
                        <a href="{% url 'homepage:homepage' %}">
                            <img class="header-logo-image" width="32px" height="32px" src="{% static 'img/saas.png' %}" alt="Logo">
                        </a>
                    </h1>
                </div>
            </div>
        </div>
    </header>

    <main>
        <section class="hero">
            <div class="container">
                <div class="hero-inner">
                    <div class="hero-copy">
                        <h1 class="hero-title mt-0">SaaShop</h1>
                        <p class="hero-paragraph">{% translate "landing_lead_text" %}</p>
                        <div class="hero-cta"><a class="button button-primary" href="{% url 'catalog:item_list' %}">{% translate "item_list" %}</a><a class="button" href="{% url "about:about" %}">{% translate "about" %}</a></div>
                    </div>
                    <div class="hero-figure anime-element">
                        <svg width="528" height="396" viewBox="0 0 528 396">
                        </svg>
                        <div class="hero-figure-box hero-figure-box-01" data-rotation="45deg"></div>
                        <div class="hero-figure-box hero-figure-box-02" data-rotation="-45deg"></div>
                        <div class="hero-figure-box hero-figure-box-03" data-rotation="0deg"></div>
                        <div class="hero-figure-box hero-figure-box-04" data-rotation="-135deg"></div>
                        <div class="hero-figure-box hero-figure-box-05"></div>
                        <div class="hero-figure-box hero-figure-box-06"></div>
                        <div class="hero-figure-box hero-figure-box-07"></div>
                        <div class="hero-figure-box hero-figure-box-08" data-rotation="-22deg"></div>
                        <div class="hero-figure-box hero-figure-box-09" data-rotation="-52deg"></div>
                        <div class="hero-figure-box hero-figure-box-10" data-rotation="-50deg"></div>
                    </div>
                </div>
            </div>
        </section>

        <section class="features section">
            <div class="container">
                <div class="features-inner section-inner has-bottom-divider">
                    <div class="features-wrap">
                        {% for feature in features %}
                            <div class="feature text-center is-revealing">
                                <div class="feature-inner">
                                    <div class="feature-icon">
                                        {% with counter_value=forloop.counter|stringformat:"s" %}
                                            <img src="{% static 'landing/img/feature-icon-0'|add:counter_value|add:'.svg' %}" alt="Feature {{ forloop.counter }}">
                                        {% endwith %}
                                    </div>
                                    <h4 class="feature-title mt-24">{{ feature.title }}</h4>
                                    <p class="text-sm mb-0">{{ feature.content }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>

        <section class="pricing section">
            <div class="container-sm">
                <div class="pricing-inner section-inner">
                    <div class="pricing-header text-center">
                        <h2 class="section-title mt-0">{% translate "subscription_title" %}</h2>
                        <p class="section-paragraph mb-0">{% translate "subscription_description" %}</p>
                    </div>
                    <div class="pricing-tables-wrap">
                        <div class="pricing-table">
                            <div class="pricing-table-inner is-revealing">
                                <div class="pricing-table-main">
                                    <div class="pricing-table-header pb-24">
                                        <div class="pricing-table-price"><span class="pricing-table-price-currency h2">$</span><span class="pricing-table-price-amount h1">49</span><span class="text-xs">/month</span></div>
                                    </div>
                                    <div class="pricing-table-features-title text-xs pt-24 pb-24">{% translate "subscription_features_title" %}</div>
                                    <ul class="pricing-table-features list-reset text-xs">
                                        <li>
                                            <span>{% translate "subscription_feature_1" %}</span>
                                        </li>
                                        <li>
                                            <span>{% translate "subscription_feature_2" %}</span>
                                        </li>
                                        <li>
                                            <span>{% translate "subscription_feature_3" %}</span>
                                        </li>
                                        <li>
                                            <span>{% translate "subscription_feature_4" %}</span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="pricing-table-cta mb-8">
                                    <a class="button button-primary button-shadow button-block" href="#">{% translate "subscription_order_button_text" %}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="cta section">
            <div class="container">
                <div class="cta-inner section-inner">
                    <h3 class="section-title mt-0">{% translate "not_sure_in_buying" %}</h3>
                    <div class="cta-cta">
                        <a class="button button-primary button-wide-mobile" href="{% url 'catalog:new_item_list' %}">{% translate "discover_new_items" %}</a>
                    </div>
                </div>
            </div>
        </section>
    </main>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <h1>{% translate "landing_item_list" %}</h1>
      <div class="row g-3 g-lg-4 g-md-3 row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-3">
        {% for item in items %}
          {% include "includes/item_card.html" %}
        {% empty %}
          <p>{% translate "no_cards" %}</p>
        {% endfor %}
      </div>
    </div>
</div>
<script src="{% static 'js/animation_setup.min.js' %}"></script>
{% endblock main %}