saashop/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [path("", views.DescriptionView.as_view(), name="about")]

saashop/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

saashop/saashop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("rating/", include("rating.urls")),
    path("statistics/", include("global_statistics.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls), name="users_default"),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT and settings.USE_LOCAL_MEDIA:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

saashop/users/urls.py
from django.contrib.auth import views
from django.urls import path

import users.forms
import users.views

app_name = "users"

urlpatterns = [
    path("signup/", users.views.UserSignupView.as_view(), name="signup"),
    path("users/", users.views.UserListView.as_view(), name="user_list"),
    path(
        "user/<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path("profile/", users.views.ProfileEditView.as_view(), name="profile"),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            form_class=users.forms.MyLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.MyPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=users.forms.MyPasswordConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "activate/<str:token>/",
        users.views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path(
        "reactivate/<str:token>/",
        users.views.ReactivateAccountView.as_view(),
        name="reactivate_account",
    ),
]

saashop/users/models.py
import sys

import django.contrib.auth.models
from django.db import models

__all__ = ()


class UserManager(django.contrib.auth.models.UserManager):
    def get_queryset(self):
        # Всегда грузим профиль
        return super().get_queryset().select_related("profile")

    def by_mail(self, email):
        return self.get_queryset().get(email=email)

    def active(self):
        return self.get_queryset().filter(is_active=True)

    def normalize_email(self, email):
        if email:
            email = email.lower()
            login, domain = email.split("@")
            if "+" in login:
                login = login.split("+")[0]
            domain = domain.replace("ya.ru", "yandex.ru")
            if domain == "yandex.ru":
                login = login.replace(".", "-")
            elif domain == "gmail.com":
                login = login.replace(".", "")
            email = f"{login}@{domain}"

        return super().normalize_email(email)


class Profile(models.Model):
    def get_path_for_file(self, filename):
        return f"avatars/{self.user_id}/{filename}"

    user = models.OneToOneField(
        django.contrib.auth.models.User,
        related_name="profile",
        on_delete=models.CASCADE,
    )
    birthday = models.DateField(
        "дата рождения",
        null=True,
        blank=True,
    )
    image = models.ImageField(
        "аватарка",
        null=True,
        blank=True,
        upload_to=get_path_for_file,
    )
    coffee_count = models.PositiveIntegerField(
        "количество выпитого кофе",
        default=0,
        blank=True,
    )
    attempts_count = models.PositiveIntegerField(
        "количество попыток входа",
        editable=False,
        default=0,
        blank=True,
    )
    blocked_timestamp = models.DateTimeField(
        verbose_name="время последней блокировки",
        null=True,
    )

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"


class User(django.contrib.auth.models.User):
    class Meta:
        proxy = True

    objects = UserManager()


def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def normalize_user_email(sender, instance, **kwargs):
    instance.email = User.objects.normalize_email(instance.email)


models.signals.post_save.connect(create_profile, sender=User)
models.signals.post_save.connect(
    create_profile,
    sender=django.contrib.auth.models.User,
)
models.signals.pre_save.connect(normalize_user_email, sender=User)
models.signals.pre_save.connect(
    normalize_user_email,
    sender=django.contrib.auth.models.User,
)

if "makemigrations" not in sys.argv and "migrate" not in sys.argv:
    User._meta.get_field("email")._unique = True
    User._meta.get_field("email").blank = False
    User._meta.get_field("email").null = False

saashop/users/forms.py
from django import forms
from django.contrib import auth

from saashop.mixins import BaseFormMixin
from users.models import Profile, User


__all__ = ()


class UserChangeForm(auth.forms.UserChangeForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta(auth.forms.UserChangeForm.Meta):
        model = User
        fields = ("username", "email", "first_name", "last_name")


class UserProfileChangeForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(UserProfileChangeForm, self).__init__(*args, **kwargs)
        self.fields["coffee_count"].widget.attrs["disabled"] = True
        self.fields["coffee_count"].widget.attrs["required"] = False
        self.fields["birthday"].widget.attrs["required"] = False
        self.set_field_attributes()

    class Meta:
        model = Profile
        fields = (
            Profile.birthday.field.name,
            Profile.image.field.name,
            Profile.coffee_count.field.name,
        )
        widgets = {
            Profile.birthday.field.name: forms.DateInput(
                attrs={"type": "date", "placeholder": "yyyy-mm-dd (DOB)"},
            ),
        }


class UserSignupForm(auth.forms.UserCreationForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta(auth.forms.UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")


class EditUserAdminForm(auth.admin.UserChangeForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        email = User.objects.normalize_email(
            email,
        )
        user_exist = (
            User.objects.filter(email=email)
            .exclude(pk=self.instance.id)
            .exists()
        )
        if user_exist:
            raise forms.ValidationError(
                "Пользователь с такой электронной почтой уже существует",
            )
        return self.cleaned_data["email"]


class CreateUserAdminForm(auth.admin.UserCreationForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        email = User.objects.normalize_email(
            email,
        )
        user_exist = (
            User.objects.filter(email=email)
            .exclude(pk=self.instance.id)
            .exists()
        )
        if user_exist:
            raise forms.ValidationError(
                "Пользователь с такой электронной почтой уже существует",
            )
        return self.cleaned_data["email"]


class MyLoginForm(auth.forms.AuthenticationForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(MyLoginForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()


class MyPasswordChangeForm(auth.forms.PasswordChangeForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()


class MyPasswordResetForm(auth.forms.PasswordResetForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(MyPasswordResetForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()


class MyPasswordConfirmForm(auth.forms.SetPasswordForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(MyPasswordConfirmForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

saashop/users/views.py
from betterforms.multiform import MultiModelForm
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.signing import BadSignature, SignatureExpired, TimestampSigner
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    View,
)

from users.forms import (
    UserChangeForm,
    UserProfileChangeForm,
    UserSignupForm,
)
import users.models


__all__ = ()


class ActivateAccountView(View):
    def get(self, request, token):
        signer = TimestampSigner()
        try:
            username = signer.unsign(
                token,
                max_age=timezone.timedelta(hours=12),
            )
            user = users.models.User.objects.get(username=username)
            user.is_active = True
            user.save()
            messages.success(
                request,
                "Аккаунт успешно активирован",
            )
        except SignatureExpired:
            messages.error(
                request,
                "Срок действия ссылки истёк :(",
            )
        except BadSignature:
            messages.error(
                request,
                "Сломанная ссылка!",
            )

        return redirect("users:login")


class ReactivateAccountView(View):
    def get(self, request, token):
        signer = TimestampSigner()
        try:
            username = signer.unsign(
                token,
                max_age=timezone.timedelta(days=7),
            )
            user = users.models.User.objects.get(username=username)
            user.is_active = True
            user.save()
            messages.success(
                request,
                "Аккаунт успешно активирован",
            )
        except SignatureExpired:
            messages.error(
                request,
                "Срок действия ссылки истёк :(",
            )
        except BadSignature:
            messages.error(
                request,
                "Сломанная ссылка!",
            )

        return redirect("users:login")


class UserSignupView(CreateView):
    template_name = "users/signup.html"
    form_class = UserSignupForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        if not self.request.user.is_authenticated:
            user = form.save(commit=False)
            user.is_active = settings.DEFAULT_USER_IS_ACTIVE
            user.save()
            self.object = user
            signer = TimestampSigner()
            token = signer.sign(user.username)
            url = self.request.build_absolute_uri(
                reverse(
                    "users:activate_account",
                    kwargs={"token": token},
                ),
            )
            send_mail(
                "Activate Your Account",
                url,
                settings.MAIL,
                [form.cleaned_data.get("email")],
                fail_silently=False,
            )

            messages.success(
                self.request,
                "Please check your email to activate your account.",
            )

            return super().form_valid(form)
        return super().form_invalid(form)


class UserListView(ListView):
    template_name = "users/user_list.html"
    model = users.models.User
    context_object_name = "users"
    queryset = users.models.User.objects.only(
        users.models.User.username.field.name,
    ).all()


class UserDetailView(DetailView):
    template_name = "users/user_detail.html"
    model = users.models.User
    context_object_name = "user"

    def get_queryset(self):
        return users.models.User.objects.select_related("profile").only(
            users.models.User.username.field.name,
            users.models.User.email.field.name,
            users.models.User.first_name.field.name,
            users.models.User.last_name.field.name,
            users.models.User.is_active.field.name,
        )


class UserProfileMultiForm(MultiModelForm):
    form_classes = {
        "user_form": UserChangeForm,
        "profile_form": UserProfileChangeForm,
    }


@method_decorator(login_required, name="dispatch")
class ProfileEditView(View):
    template_name = "users/profile.html"

    def get(self, request, *args, **kwargs):
        user_form = UserChangeForm(instance=request.user)
        profile_form = UserProfileChangeForm(instance=request.user.profile)
        return render(
            request,
            self.template_name,
            {"user_form": user_form, "profile_form": profile_form},
        )

    def post(self, request, *args, **kwargs):
        user_form = UserChangeForm(request.POST, instance=request.user)
        profile_form = UserProfileChangeForm(
            request.POST,
            request.FILES,
            instance=request.user.profile,
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully!")
            return redirect("users:profile")

        return render(
            request,
            self.template_name,
            {"user_form": user_form, "profile_form": profile_form},
        )

saashop/templates/users/login.html
{% extends "base.html" %}
{% block main %}
{% load i18n %}

<div class="container">
    <h1>{% translate "login_html" %}</h1>
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="{% translate 'send' %}">
    </form>
    <br>
    <p>{% translate "dont_have_an_account_yet" %} <a class="bold" href="{% url 'users:signup' %}">{% translate "signup_action" %}</a></p>
    <a class="bold" href="{% url 'users:password_reset' %}">{% translate "forgot_password" %}</a>
</div>

{% endblock %}

saashop/templates/users/logout.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h2>Выход выполнен</h2>
    <p>Вы успешно вышли из аккаунта</p>
</div>

{% endblock %}

saashop/templates/users/password_change.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h1>Изменение пароля</h1>
    <form method="post" action="{% url 'users:password_change' %}">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="Изменить пароль">
    </form>
</div>

{% endblock %}

saashop/templates/users/password_change_done.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h2>Пароль успешно изменён</h2>
    <p>Ваш пароль успешно изменён</p>
</div>

{% endblock %}

saashop/templates/users/password_reset.html
{% extends "base.html" %}
{% block main %}
{% load i18n %}

<div class="container">
    <h1>{% translate 'reset_password' %}</h1>
    <form method="post" action="{% url 'users:password_reset' %}">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="{% translate 'reset_password_action' %}">
    </form>
</div>

{% endblock %}

saashop/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h2>Пароль успешно сброшен</h2>
    <p>Ваш пароль был успешно сброшен</p>
</div>

{% endblock %}

saashop/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h1>Подтвердите сброс пароля</h1>
    <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="Подтвердить сброс пароля">
    </form>
</div>

{% endblock %}

saashop/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block main %}

<div class="container">
    <h2>Письмо отправлено</h2>
    <p>Мы отправили письмо с инструкциями по сбросу пароля на указанную вами почту</p>
</div>

{% endblock %}

saashop/templates/users/profile.html
{% extends "base.html" %}

{% block main %}
<div class="container">
  <h1>Мой профиль</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {% with user_form as form %}
    {% include "includes/form.html" %}
      {% endwith %}
    {% with profile_form as form %}
      {% include "includes/form.html" %}
    {% endwith %}
    <input class="btn btn-primary" type="submit" value="Сохранить">
  </form>
  <hr>
  <a href="{% url 'homepage:coffee' %}">Выпить кофе</a>
</div>
{% endblock %}

saashop/templates/users/signup.html
{% extends "base.html" %}
{% block main %}
{% load i18n %}

<div class="container">
    <h1>{% translate "registration" %}</h1>
    <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" %}
        <input class="btn btn-primary" type="submit" value="{% translate 'send' %}">
    </form>
    <br>
    <p>{% translate "already_have_an_account" %} <a class="bold" href="{% url 'users:login' %}">{% translate "login" %}</a></p>
</div>

{% endblock %}

saashop/templates/users/user_detail.html
{% extends "base.html" %}

{% block main %}
<div class="container">
  <h2>Информация о пользователе по его id</h2>
  <dl>
    <dt>Имя пользователя:</dt>
    <dd>{{ user.username }}</dd>

    <dt>Почта:</dt>
    <dd>{{ user.email }}</dd>

    <dt>Имя:</dt>
    <dd>{{ user.first_name|default:"Не указано" }}</dd>

    <dt>Фамилия:</dt>
    <dd>{{ user.last_name|default:"Не указано"}}</dd>

    <dt>Активен:</dt>
    <dd>{{ user.is_active|yesno:"Да,Нет" }}</dd>

    <dt>Дата рождения:</dt>
    <dd>{{ user.profile.birthday|default:"Не указано" }}</dd>

    <dt>Аватар:</dt>
    <dd>
      {% if user.profile.image %}
      <img src="{{ user.profile.image.url }}" alt="User Image" width="100">
      {% else %}
      Отсутствует
      {% endif %}
    </dd>

    <dt>Количество выпитых кофе:</dt>
    <dd>{{ user.profile.coffee_count }}</dd>
  </dl>
</div>
{% endblock %}

saashop/templates/users/user_list.html
{% extends "base.html" %}

{% block main %}
<div class="container">
  <h2>Список пользователей</h2>
  <ul>
    {% for user in users %}
      <li><a href="{% url 'users:user_detail' user.id %}">{{ user.username }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}