saashop/about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [path("", views.DescriptionView.as_view(), name="about")]

saashop/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"
urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="item_list",
    ),
    path(
        "new/",
        views.NewItemListView.as_view(),
        name="new_item_list",
    ),
    path(
        "friday/",
        views.FridayItemListView.as_view(),
        name="friday_item_list",
    ),
    path(
        "unverified/",
        views.UnverifiedItemListView.as_view(),
        name="unverified_item_list",
    ),
    path(
        "<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
]

saashop/download/urls.py
from django.urls import path

from download import views

app_name = "download"
urlpatterns = [
    path("<path:path>", views.DownloadView.as_view(), name="download"),
]

saashop/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

saashop/saashop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("rating/", include("rating.urls")),
    path("statistics/", include("global_statistics.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include(django.contrib.auth.urls), name="users_default"),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT and settings.USE_LOCAL_MEDIA:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

saashop/catalog/models.py
from datetime import datetime
from pathlib import Path
import uuid

from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
)
from django.db import models
from django.utils.html import mark_safe
from django.utils.translation import gettext_lazy as _
import django_cleanup
import sorl.thumbnail
from tinymce.models import HTMLField

from catalog.validators import ValidateMustContain
from core.models import AddUniqueName, CoreModel

__all__ = ()

BASE_DIR = Path(__file__).resolve().parent.parent


def get_file_path_for_main_image(instance, filename):
    filename = str(uuid.uuid4()) + "." + filename.split(".")[-1]
    return "main_image/{0}/{1}".format(
        datetime.now().strftime("%Y.%m.%d"),
        filename,
    )


def get_file_path_for_images(instance, filename):
    filename = str(uuid.uuid4()) + "." + filename.split(".")[-1]
    return "images/{0}/{1}".format(
        datetime.now().strftime("%Y.%m.%d"),
        filename,
    )


class Tag(CoreModel, AddUniqueName):
    slug = models.SlugField(
        _("slug_models"),
        max_length=200,
        unique=True,
        help_text="a-z, 0-9, _, -",
    )

    class Meta:
        verbose_name = _("tag_models")
        verbose_name_plural = _("tags_models")


class Category(CoreModel, AddUniqueName):
    slug = models.SlugField(
        _("slug_models"),
        max_length=200,
        unique=True,
        help_text="a-z, 0-9, _, -",
    )
    weight = models.PositiveSmallIntegerField(
        _("weight_models"),
        default=100,
        validators=[MinValueValidator(1), MaxValueValidator(32767)],
    )

    class Meta:
        verbose_name = _("category_models")
        verbose_name_plural = _("categories_models")


class MainImage(models.Model):
    main_image = models.ImageField(
        _("image_models"),
        upload_to=get_file_path_for_main_image,
    )

    def get_image_300x300(self):
        return sorl.thumbnail.get_thumbnail(
            self.main_image,
            "300x300",
            quolity=51,
        )

    def get_thumbnail(
        self,
        thumb_height=300,
        thumb_width=300,
        thumb_quality=51,
    ):
        return sorl.thumbnail.get_thumbnail(
            self.main_image,
            f"{thumb_width}x{thumb_height}",
            quality=thumb_quality,
        )

    def image_tmb(self):
        if self.main_image:
            return mark_safe(
                f"<img src='{self.get_image_300x300().url}' width='300'",
            )
        return _("no_image")

    image_tmb.short_description = _("preview")
    image_tmb.allow_tags = True

    def __str__(self) -> str:
        verbose = _("main_image_models").capitalize()
        return f"{verbose}, ID:{self.id}"

    class Meta:
        verbose_name = _("main_image_models")
        verbose_name_plural = _("main_images_models")


class ItemManager(models.Manager):
    def on_main(self):
        return (
            self.get_queryset()
            .select_related(Item.category.field.name)
            .filter(
                is_on_main=True,
                is_published=True,
                category__is_published=True,
            )
            .prefetch_related(
                models.Prefetch(
                    Item.tags.field.name,
                    queryset=Tag.objects.filter(is_published=True)
                    .order_by(Tag.name.field.name)
                    .only(
                        Tag.name.field.name,
                    ),
                ),
            )
            .only(
                Item.id.field.name,
                Item.name.field.name,
                Item.text.field.name,
                f"{Item.category.field.name}__{Category.name.field.name}",
            )
        )

    def published(self):
        return (
            self.get_queryset()
            .select_related(Item.category.field.name)
            .prefetch_related(
                models.Prefetch(
                    Item.tags.field.name,
                    queryset=Tag.objects.filter(is_published=True)
                    .order_by(Tag.name.field.name)
                    .only(
                        Tag.name.field.name,
                    ),
                ),
            )
            .filter(is_published=True, category__is_published=True)
            .only(
                Item.id.field.name,
                Item.name.field.name,
                Item.text.field.name,
                f"{Item.category.field.name}__{Category.name.field.name}",
            )
            .order_by(
                f"{Item.category.field.name}__{Category.name.field.name}",
            )
        )

    def item_detail(self, item_id):
        return (
            self.get_queryset()
            .filter(id=item_id)
            .select_related(Item.category.field.name)
            .select_related(Item.main_image.field.name)
            .prefetch_related(
                models.Prefetch(
                    Item.tags.field.name,
                    queryset=Tag.objects.filter(is_published=True)
                    .order_by(Tag.name.field.name)
                    .only(
                        Tag.name.field.name,
                    ),
                ),
            )
            .prefetch_related(
                models.Prefetch(
                    "images",
                    queryset=ItemImages.objects.only(
                        ItemImages.image.field.name,
                        "item_id",
                    ),
                ),
            )
            .filter(is_published=True, category__is_published=True)
            .only(
                Item.id.field.name,
                Item.name.field.name,
                Item.text.field.name,
                f"{Item.category.field.name}__{Category.name.field.name}",
                (
                    f"{Item.main_image.field.name}__"
                    f"{MainImage.main_image.field.name}"
                ),
            )
        )


class Item(CoreModel):
    objects = ItemManager()

    is_on_main = models.BooleanField(_("show_on_main_models"), default=False)
    text = HTMLField(
        _("text_models"),
        validators=[
            ValidateMustContain(
                "превосходно",
                "роскошно",
                "perfect",
                "luxurious",
            ),
        ],
        help_text=(_("text_should_contain")),
    )
    created_at = models.DateTimeField(
        _("created_at_utc_models"),
        null=True,
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        _("updated_at_utc_models"),
        null=True,
        auto_now=True,
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name=_("tags_models"),
        blank=True,
        related_query_name="tag",
        help_text=_("choose_tags_non_required"),
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        verbose_name=_("category_models"),
        blank=True,
        related_name="item",
        related_query_name="category",
        help_text=_("choose_category_non_required"),
    )
    main_image = models.OneToOneField(
        MainImage,
        verbose_name=_("main_image_models"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("name", "id")
        verbose_name = _("item_models")
        verbose_name_plural = _("items_models")


class ItemImages(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.SET_NULL,
        null=True,
        related_query_name="images",
        verbose_name=_("item_models"),
        related_name="images",
    )
    image = models.ImageField(
        _("image_models"),
        upload_to=get_file_path_for_images,
        null=True,
    )

    def get_thumbnail(
        self,
        thumb_height=300,
        thumb_width=300,
        thumb_quality=51,
    ):
        return sorl.thumbnail.get_thumbnail(
            self.image,
            f"{thumb_width}x{thumb_height}",
            quality=thumb_quality,
        )

    def image_tmb(self):
        if self.image:
            return mark_safe(
                f"<img src='{self.get_thumbnail().url}' width='300'",
            )
        return _("no_image")

    image_tmb.short_description = _("preview")
    image_tmb.allow_tags = True

    def __str__(self) -> str:
        verbose = _("item_image_models").capitalize()
        return f"{verbose}, ID:{self.id}"

    class Meta:
        verbose_name = _("item_image_models")
        verbose_name_plural = _("item_images_models")


def sorl_delete(**kwargs):
    sorl.thumbnail.delete(kwargs["file"])


django_cleanup.signals.cleanup_pre_delete.connect(sorl_delete)

saashop/catalog/views.py
from datetime import timedelta

from django.contrib import messages
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView

import catalog.models
from rating.forms import RatingForm
from rating.models import get_rating_stats, Rating

__all__ = ()


class ItemListView(ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"

    def get_queryset(self):
        return catalog.models.Item.objects.published()


class NewItemListView(ItemListView):
    template_name = "catalog/item_list.html"

    def get_queryset(self):
        one_week_ago = timezone.now() - timedelta(days=7)
        ids = (
            catalog.models.Item.objects.published()
            .filter(created_at__gte=one_week_ago)
            .values_list("id", flat=True)
            .order_by("?")[:5]
        )
        return (
            (
                catalog.models.Item.objects.published()
                .filter(id__in=ids)
                .order_by("category", "name")
            )
            if ids
            else None
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("new_items")
        return context


class FridayItemListView(ItemListView):
    template_name = "catalog/item_list.html"

    def get_queryset(self):
        ids = (
            catalog.models.Item.objects.published()
            .filter(updated_at__week_day=6)
            .values_list("id", flat=True)
            .order_by("-updated_at")[:5]
        )
        return (
            (
                catalog.models.Item.objects.published()
                .filter(id__in=ids)
                .order_by("category", "name")
            )
            if ids
            else None
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("friday")
        return context


class UnverifiedItemListView(ItemListView):
    template_name = "catalog/item_list.html"

    def get_queryset(self):
        return catalog.models.Item.objects.published().filter(
            created_at=models.F("updated_at"),
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("unverified")
        return context


class ItemDetailView(DetailView):
    template_name = "catalog/item.html"

    def get(self, request, pk):
        item_id = self.kwargs.get("pk")

        item = get_object_or_404(
            Rating.objects.get_item_with_rating(pk),
            pk=item_id,
        )

        ratings = item.ratings.all()

        avg_rating = get_rating_stats(ratings)
        user_rating = None
        if request.user.is_authenticated:
            user_rating = Rating.objects.get_rating_by_item_and_user(
                request.user.id,
                pk,
            ).first()
        form = RatingForm(instance=user_rating)

        context = {
            "item": item,
            "avg_rating": avg_rating,
            "form": form,
        }
        return render(
            request,
            template_name=self.template_name,
            context=context,
        )

    def post(self, request, pk):
        item_id = self.kwargs.get("pk")
        item = get_object_or_404(
            Rating.objects.get_item_with_rating(pk),
            pk=item_id,
        )
        form = RatingForm(request.POST)
        user_rating = None

        if request.user.is_authenticated:
            user_rating = Rating.objects.get_rating_by_item_and_user(
                request.user.id,
                pk,
            ).first()
        else:
            messages.error(
                request,
                "Пользователь не авторизован",
            )
            redirect("catalog:item_detail", pk=pk)

        if form.is_valid():
            if user_rating:
                user_rating.text = form.cleaned_data["text"]
                user_rating.rating = form.cleaned_data["rating"]
                user_rating.save()
                return redirect("catalog:item_detail", pk=pk)
            rating = form.save(commit=False)
            rating.user = request.user
            rating.item = item
            rating.save()
        return redirect("catalog:item_detail", pk=pk)

saashop/templates/catalog/item.html
{% extends "base.html" %}
{% block main %}
{% load thumbnail static i18n %}
<script src="{% static 'js/anime.min.js' %}"></script>
<script src="{% static 'js/scrollreveal.min.js' %}"></script>
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5">
            {% thumbnail item.main_image.main_image "300x300" as main_image %}
            <div class="col-md-6">
                <div class="card item_card is-revealing mb-3">
                    <a href="{% url 'download:download' path=item.main_image.main_image %}">
                        <div class="badge bg-warning text-black position-absolute download_image">
                            <i class="fa-solid fa-download"></i>
                        </div>
                    </a>
                    <img width="300px" class="card-img-top mb-md-0 rounded" src="{{ main_image.url }}">
                </div>
            </div>
            {% empty %}
            <div class="col-md-6">
                <div class="card item_card is-revealing mb-3">
                    <svg height="300px" max-width="300px" class="card-img-top mb-md-0 rounded" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>{% translate "no_image" %}</title>
                        <rect width="100%" height="100%" fill="#55595c"></rect>
                    </svg>
                </div>
            </div>
            {% endthumbnail %}
            <div class="col-sm-6">
                <h1 class="display-5 fw-bolder no-margin-top">{{ item.name }}</h1>
                <p class="lead">{{ item.text|safe }}</p>
                <h6>{% translate "rating" %}:</h6>
                {% if avg_rating.count %}
                    <div class="row">
                        <div class="col">
                            Общий
                        </div>
                        <div class="col">
                            {{ avg_rating.avg }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            Отзывы
                        </div>
                        <div class="col">
                            {{ avg_rating.count }}
                        </div>
                    </div>
                {% else %}
                    <p text-secondary user-select-none>{% translate "empty" %}</p>
                {% endif %}
                <h6>{% translate "category" %}:</h6>
                <span class="badge rounded-pill text-bg-warning">{{ item.category.name }}</span>
                <h6>{% translate "tags" %}:</h6>
                {% for tag in item.tags.all %}
                    <span class="badge rounded-pill text-bg-warning">{{ tag.name }}</span>
                {% empty %}
                    {% translate "empty_plural" %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<section class="py-3 bg-dark">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">{% translate "images" %}:</h2>
        <div class="row g-3 g-lg-4 g-md-3 row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-3 justify-content-center">
            {% for image in item.images.all %}
            {% thumbnail image.image "300x300" as tmb_image %}
            <div class="col mb-5">
                <div class="card item_card is-revealing zoomable-card">
                    <a href="{% url 'download:download' path=image.image %}">
                        <div class="badge bg-warning text-black position-absolute download_image">
                            <i class="fa-solid fa-download"></i>
                        </div>
                    </a>
                    <img class="card-img-top card-img-bottom" src="{{ tmb_image.url }}">
                </div>
            </div>
            {% endthumbnail %}
            {% empty %}
            </div>
            <p class="margin-top-10px">{% translate "empty_plural" %}</p>
            <div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="py-5">
    <div class="container">
        {% if user.is_authenticated %}
            {% if form.instance.pk is None %}
            <h2>Оставить отзыв:</h2>
            <form method="post">
                {% csrf_token %}
                {% include "includes/form.html" %}
                <input class="btn btn-primary" type="submit" value="Отправить">
            </form>
            {% endif %}
        {% endif %}
        <h3>Отзывы</h3>
        {% for rating in item.ratings.all %}
            {% include "includes/rating.html" %}
            {% empty %}
            <p class="margin-top-10px">{% translate "empty_plural" %}</p>
        {% endfor %}
    </div>
</section>
<script src="{% static 'js/animation_setup.min.js' %}"></script>
{% endblock %}

saashop/templates/catalog/item_list.html
{% extends "base.html" %}
{% block main %}
{% load static i18n %}
<script src="{% static 'js/anime.min.js' %}"></script>
<script src="{% static 'js/scrollreveal.min.js' %}"></script>
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">SaaShop</h1>
      <p class="lead text-body-secondary">{% translate "item_list_lead_text" %}</p>
      <p>
        <a href="{% url 'homepage:homepage' %}" class="btn btn-primary my-2">{% translate "home" %}</a>
        <a href="{% url 'about:about' %}" class="btn btn-secondary my-2">{% translate "about" %}</a>
      </p>
    </div>
  </div>
</section>
<div class="album py-4 bg-body-tertiary">
  <div class="container">
    <h1>{{ title }}</h1>
    <div>
      {% for item in items %}
      {% ifchanged %}
        </div>
        <h2>{{ item.category }}</h2>
        <div class="row g-3 g-lg-4 g-md-3 row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-xl-3">
      {% endifchanged %}
        {% include "includes/item_card.html" %}
      {% empty %}
        <p>{% translate "no_cards" %}</p>
      {% endfor %}
    </div>
  </div>
</div>
<script src="{% static 'js/animation_setup.min.js' %}"></script>
{% endblock main %}